# Generated by Django 3.0.8 on 2020-08-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='languages',
        ),
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.TextField(default='long description'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(default='short description'),
        ),
    ]
